### ISSUE TITLE
添加 pink_1.csv 时卡在预览页面

### ISSUE THREAD

**Issue by kongwy** [mariotaku/wtb#6]
添加 pink_1.csv 时一直卡在预览页面，用在线的 Twitter ID Username converter 检查后删去一个看上去是英文认证推和一个不存在推，并顺便（手动）加上几个最近已 block 的小粉红（变更已发 pull 请检阅），然而更改后的 pink_1.csv 依然卡在预览，麻烦网红检查。

**Comment by DrayChou** [comment]
你查看下是不是有某一行是空行？官方导入脚本不识别空行，有空行在就会JS报错死在那里。

**Comment by kongwy** [comment]
刚知道……
